version: '2.1'
services:
  prueba-postgres:
    container_name: prueba-postgres
    image: 'postgres'
    environment:
      POSTGRES_DB: carrocompra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    restart: always
    networks:
      - back-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  prueba-app:
    image: prueba-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    networks:
      - back-tier
    depends_on:
      prueba-postgres:
          condition: service_healthy
networks:
  back-tier:
    driver: bridge